apiVersion: apps/v1
kind: Deployment
metadata:
  name: Purchase
  labels:
    app: Purchase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Purchase
  template:
    metadata:
      labels:
        app: Purchase
    spec:
      containers:
        - name: Purchase
          image: username/Purchase:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5